=for header
manpage:  UPDATE-LILO
section:  8
title:    lilo documentation
version:  24.0
datum:    2013-06-07

=encoding utf8

=head1 NAME

update-lilo - execute lilo in special debconf mode

=head1 SYNOPSIS

B<update-lilo>

=head1 DESCRIPTION

This special script only execute lilo with sending all output to >$2

=head1 COPYRIGHT and LICENSE

Copyright (C) 2010-2013 Joachim Wiedorn

This script is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by 
the Free Software Foundation; either version 2 of the License, or 
(at your option) any later version.

On Debian systems, the complete text of the GNU General Public
License version 2 can be found in `/usr/share/common-licenses/GPL-2'.

=head1 AUTHOR

B<update-lilo> was written by Joachim Wiedorn.

This manual page was written by Joachim Wiedorn <ad_debian at joonet.de>
for the Debian project (and may be used by others).

=head1 SEE ALSO

B<lilo>(8), B<lilo-uuid-diskid>(1), B<liloconfig>(8)

=cut
